[tool.black]
exclude = '''
(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.eggs
  | _pb2\.py
)
'''
target_version = ['py36', 'py37']
line-length = 120
